### ISSUE TITLE
I don't get dynamic tab-headers

### ISSUE THREAD

**Issue by schorsch3000** [Morgul/vueboot#1]
Hi, i tryeds vueboot since i cant get vue-strap to work with webpack/vue-loader.
vueboot seems to work fine with them, but something is odd with the tab-headers:
i have:

``` javascript
    var vueboot = require('vueboot');
    window.addEventListener('load', function () {
        var app = new Vue({
            components: {
                'tab': vueboot.tab,
                'tabset': vueboot.tabset
            },
            data:{
                tabs:[
                    {"tab_name":"test1"},
                    {tab_name:"test2"}
                ]
            }
```

and the template:

``` html
   <tabset>
            <tab v-for="tab in tabs" header="{{tab.tab_name}}">
    <tabset>
```

no i literally get the tabname {{tab.tab_name}}

do i something wrong here?

**Comment by Morgul** [comment]
Looks like you forgot to bind the property:

`:header="{{tab.tab_name}}"`

Note the colon, which is missing in your template. So, you template should just be: 

``` html
<tabset>
    <tab v-for="tab in tabs" :header="{{tab.tab_name}}">
<tabset>
```

Alternatively, you can use the `v-bind` syntax:

``` html
<tabset>
    <tab v-for="tab in tabs" v-bind:header="{{tab.tab_name}}">
<tabset>
```

Please see: http://vuejs.org/guide/syntax.html#v-bind_Shorthand

**Comment by Morgul** [comment]
@schorsch3000: Let me know if that works for you, and I'll close the issue. :)

**Comment by Morgul** [comment]
Closing the issue because I haven't heard back. Feel free to reopen if there's still a problem. :)
