### ISSUE TITLE
`:timeout` not working

### ISSUE THREAD

**Issue by juannenna** [Morgul/vueboot#10]
Hi! maybe im doing something wrong, but i tried using the alerts with timeout and they are never being dismissed.

`<alert type="danger" :timeout="4000">
      This message should time out after 4 seconds.
    </alert>`

I get no errors, but the alert is simply not dissappearing

thanks!

**Comment by Morgul** [comment]
What you have there looks right. The demo site still works:

http://morgul.github.io/vueboot/#alert

So, it must be something with your setup (or new versions of a library, etc, etc). Could you reproduce this in a [codePen](http://codepen.io/), so I can take a look?

**Comment by juannenna** [comment]
sure! im working on preparing the codePen right now. As far as setup goes: 

node: ">= 4.0.0"
npm: ">= 3.0.0"
vueboot: "^0.4.5"
vue: "^2.0.3",


as soon as i get the pen ill post it. thanks!

**Comment by Morgul** [comment]
Ah, I can already see your issue: vue 2. I haven't updated this library for vue 2 yet. (It's been that long since I worked on it.) It honestly shouldn't be hard (and the update would fix several other bugs). If you'd like to lend a hand updating the components, I'll definitely take that, but I'll probably get around to it myself anyway.

**Comment by juannenna** [comment]
ahhh ok, yeah, that figures. Um, sure i can try! :D don't know exactly how i can help but if i can in any way, i will!

**Comment by Morgul** [comment]
This is a great guide:

https://vuejs.org/v2/guide/migration.html

I'd start by doing a component at a time; say, start with 'alert', and update the code in `src/alert/alter.vue`. Then update `examples/alert.html` to use Vue2 and test using that page.

My plan is to make development easier, but right now that's the simplest place to get started.

**Comment by juannenna** [comment]
oh ok! as soon as i have a minute ill check it out! thanks!

**Comment by juannenna** [comment]
hey! I updated the alert.vue file and now it works perfectly! all that was needed was to replace "ready {}" for "mounted"

**Comment by Morgul** [comment]
Cool. Can you send in a pull request? That will at least start the conversion to vue 2.

**Comment by Morgul** [comment]
So, I started working on updating things like the documentation site, etc, and I found this:

https://github.com/bootstrap-vue/bootstrap-vue

That's a much more active, better maintained and more complete version of VueBoot. 😕

**Comment by juannenna** [comment]
oh yeah, i just checked it out. looks pretty solid haha i still like vueBoot a lot tho!! :D
