### ISSUE TITLE
ReferenceError: $ is not defined while trying to use alert

### ISSUE THREAD

**Issue by schlitzered** [Morgul/vueboot#3]
hey, i am trying myself to get startet with vue.js & javascript

i used vue-cli to get up and running with the webpack sample project.

i added a view Bar that looks like this:

```
<template>
  <nav-component></nav-component>
  <div class="hello-bar">
    <h1>{{ msg }}</h1>
    <h4>Static</h4>
    <alert type="info" :dismissible="false">
      This is an <strong>info</strong> alert.
    </alert>
    <h4>Timeout</h4>
    <button class="btn btn-primary" @click="showAlert()">ShowAlert</button>
    <alert v-if="show" type="danger" :timeout="4000" :on-closed="onClosed">
      This message should time out after 4 seconds.
    </alert>
  </div>
</template>

<script>
  import { alert } from 'vueboot'

  export default {
    components: {
      alert: alert
    },
    data () {
      return {
        msg: 'Hello Bar World!',
        show: false
      }
    },
    methods: {
      onClosed: function () {
        console.log('onClosed!')
        this.show = false
      },
      showAlert: function () {
        this.show = true
      }
    }
  }
</script>
```

but for some reason the two alerts i have wont work as expected.

i just get the error "ReferenceError: $ is not defined while trying to use alert" in the console.

triggering the second alert will successfully show the alert, but it wont hide after 4 seconds.

Kind Regards,

Stephan

**Comment by Morgul** [comment]
Do you have jQuery being loaded before using `alert`? If you just started with vue-cli, I'm guessing that's missing (it's a dependency of VueBoot, not Vue in general).

Try adding jQuery to you project first, and make sure in the console you can type `$` and get:

```
> $
function ( selector, context ) {
        // The jQuery object is actually just the init constructor 'enhanced'
        return new jQuery.fn.init( selector, context, rootjQuery );
    }
```

**Comment by schlitzered** [comment]
thanks for the answer, it seems taht jquery is indeed not loaded, i added it to package.json, but calling "$" in the console, but it only gives back "function()"

i tired to google it, but have not been able to find out how i should load jquery with vue. could you please give me a hint?

**Comment by Morgul** [comment]
Sure. :)

Loading jquery has nothing to do with vue, which is why you're struggling. Instead, you would need to figure out how to correctly configure Webpack. I'm not super familiar with Webpack (I've never used it), but I'd head in that direction.

Once you figure out jQuery, Bootstrap also requires `tether`, so you'll need to do the same thing for it.

For now, I'd recommend just putting these two lines in your `body` tag, and see if everything else just works:

``` html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.1/js/tether.min.js"></script>
```

If it does, then you can work on figuring out how to make webpack expose jquery and tether as globals for Bootstrap's js to pick up on. (They have to be globals, currently, due to how Bootstrap v4's javascript is written, unfortunately.)

**Comment by Morgul** [comment]
Btw, I recommend taking a look at the examples:

https://github.com/Morgul/vueboot/blob/master/examples/alert.html

**Comment by schlitzered** [comment]
thank for your input, i managed to get jquery & tether globally available via webpack,

but now i get the following error, after the 4 seconds timeout:

TypeError: $(...).alert is not a function

**Comment by Morgul** [comment]
Ah, you aren't including the Bootstrap v4 javascript.

**Comment by schlitzered** [comment]
arg! yes, that did the trick. thank you so much for your help, i am a total newbie when it comes to web developement and all this css, html, javascript stuff \o/

this ticket can get closed now

**Comment by Morgul** [comment]
No problem! We all have to start somewhere. :)
